/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.arch.lifecycle.livedata.core;
import javax.annotation.Nullable;
public final class R {
}
